# Generated by Django 5.0.7 on 2024-08-13 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbridge', '0002_groupmessage_group_groupthread_groupmessage_thread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupthread',
            name='first_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_message_in_thread', to='techbridge.groupmessage'),
        ),
    ]
